import { type NextPage } from "next";
import Head from "next/head";

import { Section } from "@ui/Section";
import { Container } from "@ui/Container";
import { Typography } from "@ui/Typography";
import { AppNavHeader } from "@/components/composite/AppNavHeader";

import { PUBLIC } from "@/config/routes";
import { Card, CardContent, CardLink } from "@ui/Card";
import { Figure } from "@ui/Figure";
import { Link } from "@ui/Link";

import { motion } from "framer-motion";

import { FiExternalLink } from "react-icons/fi";

import {
  SiNextdotjs,
  SiReact,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";
import {
  fadeAndSlideInFromLeft,
  fadeAndSlideInFromRight,
} from "@/utils/animations";
import { SplitContainer, SplitItem } from "@ui/Split";
import { RadixUiLogo } from "@/components/svgs/RadixUiLogo";
import { ReactHookFormLogo } from "@/components/svgs/ReactHookFormLogo";
import { ZodLogo } from "@/components/svgs/ZodLogo";
import { TanStackLogo } from "@/components/svgs/TanStackLogo";
import { CvaLogo } from "@/components/svgs/CvaLogo";
import { FramerLogo } from "@/components/svgs/FramerLogo";
import { AuthJsLogo } from "@/components/svgs/AuthJsLogo";
import { SiPrisma } from "react-icons/si";
import { T3Logo } from "@/components/svgs/T3Logo";
import { TrpcLogo } from "@/components/svgs/TrpcLogo";

const Page: NextPage = () => {
  const CONTENT = {
    hero: {
      heading: "Max Randle",
      body: "Find out a little bit about me, download my résumé, and play around with my embedded projects.",
      media: PUBLIC.media.maxProfilePicture,
    },
    workSection: {
      heading: "My work",
      body: "I am a Front-End Software Engineer with a passion for creating fast, responsive, seamless, and accessible web applications. I value readability, consistency, simplicity, and agnosticism as the core paradigms of my coding mantra. These values are reflected in my work as I produce code that scales well and is easily maintainable.",
      action: "Résumé",
      media: PUBLIC.media.maxArtExhibit,
    },
    stack: {
      heading: "My Front-End stack",
      tech: [
        {
          icon: SiTypescript,
          name: "TypeScript",
          description:
            "TypeScript is essential and JavaScript is not a viable language for building production applications.",
        },
        {
          icon: SiReact,
          name: "React 18",
          description:
            "This legendary framework continues to make new strides as it rises into its third great era with the introduction of server components.",
        },
        {
          icon: SiNextdotjs,
          name: "Next 13",
          description:
            "What better way to build an application than with the tools and capabilities afforded by Next.js?",
        },
        {
          icon: SiTailwindcss,
          name: "TailwindCSS",
          description:
            "The best thing to happen to CSS since flexbox. Much more than syntax, Tailwind is a design system all on its own.",
        },
      ],
    },
    toolkit: {
      heading: "Favourite tools and libraries",
      tools: [
        {
          name: "TanStack Query",
          icon: TanStackLogo,
          url: "https://tanstack.com/query/latest",
        },
        {
          name: "Auth.js",
          icon: AuthJsLogo,
          url: "https://authjs.dev/",
        },
        {
          name: "React Hook Form",
          icon: ReactHookFormLogo,
          url: "https://react-hook-form.com/",
        },
        {
          name: "Zod",
          icon: ZodLogo,
          url: "https://zod.dev/",
        },
        {
          name: "Framer Motion",
          icon: FramerLogo,
          url: "https://www.framer.com/motion/",
        },
        {
          name: "Radix UI",
          icon: RadixUiLogo,
          url: "https://www.radix-ui.com/",
        },
        {
          name: "Prisma",
          icon: SiPrisma,
          url: "https://www.prisma.io/",
        },
        {
          name: "Create T3 App",
          icon: T3Logo,
          url: "https://create.t3.gg/",
        },
        {
          name: "Class Variance Authority",
          icon: CvaLogo,
          url: "https://cva.style/docs",
        },
        {
          name: "tRPC",
          icon: TrpcLogo,
          url: "https://trpc.io/",
        },
      ],
    },
  };

  const MotionSplitContainer = motion(SplitContainer);
  const MotionSplitItem = motion(SplitItem);
  const MotionCardLink = motion(CardLink);
  const MotionDiv = motion.div;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen overflow-hidden">
        <AppNavHeader />
        <Section>
          <Container>
            <MotionSplitContainer
              className="mt-10"
              variants={{
                visible: {
                  transition: {
                    delayChildren: 0,
                    staggerChildren: 0.5,
                  },
                },
              }}
              initial="hidden"
              animate="visible"
            >
              <MotionSplitItem side="right" variants={fadeAndSlideInFromRight}>
                <Typography
                  className="text-center md:text-left"
                  level="heading1"
                >
                  {CONTENT.hero.heading}
                </Typography>
              </MotionSplitItem>
              <MotionSplitItem
                className="row-span-2"
                side="left"
                variants={fadeAndSlideInFromLeft}
              >
                <Figure
                  className="mx-auto aspect-square max-h-60 min-h-[12rem] rounded-full"
                  src={CONTENT.hero.media}
                  alt="me"
                  width={160}
                  height={160}
                />
              </MotionSplitItem>
              <MotionSplitItem side="right" variants={fadeAndSlideInFromRight}>
                <Typography
                  className="mx-auto max-w-xl text-center md:text-left"
                  level="heading3"
                  color="weaker"
                >
                  {CONTENT.hero.body}
                </Typography>
              </MotionSplitItem>
            </MotionSplitContainer>
          </Container>
        </Section>

        <Container>
          <hr className="border-base-400 dark:border-base-1300" />
        </Container>

        <Section>
          <Container className="text-center md:text-left">
            <Card>
              <CardContent>
                <SplitContainer>
                  <SplitItem side="left">
                    <Typography level="heading2">
                      {CONTENT.workSection.heading}
                    </Typography>
                  </SplitItem>
                  <SplitItem className="row-span-3" side="right">
                    <Figure
                      className="mx-auto aspect-square max-w-xs rounded-full"
                      src={CONTENT.workSection.media}
                      alt="me"
                      width={320}
                      height={320}
                    />
                  </SplitItem>
                  <SplitItem side="left">
                    <Typography className="mx-auto max-w-xl" color="weaker">
                      {CONTENT.workSection.body}
                    </Typography>
                  </SplitItem>
                  <SplitItem side="left">
                    <Link
                      className="inline-flex items-center gap-2 text-xl"
                      href={PUBLIC.documents.resume}
                      target="_blank"
                    >
                      <p>{CONTENT.workSection.action}</p>
                      <FiExternalLink />
                    </Link>
                  </SplitItem>
                </SplitContainer>
              </CardContent>
            </Card>
          </Container>
        </Section>

        <Section palette={"surface"}>
          <Container>
            <Typography level={"heading2"}>{CONTENT.stack.heading}</Typography>
            <div className="mt-20 grid gap-4 sm:grid-cols-2">
              {CONTENT.stack.tech.map(({ description, icon: Icon, name }) => (
                <Card palette={"base"} key={name}>
                  <CardContent>
                    <Icon size={40} />
                    <Typography level={"subheading"} className="mt-4">
                      {name}
                    </Typography>
                    <Typography
                      color={"weaker"}
                      level={"caption"}
                      className="mt-4"
                    >
                      {description}
                    </Typography>
                  </CardContent>
                </Card>
              ))}
            </div>
          </Container>
        </Section>

        <Section>
          <Container className="mx-auto max-w-3xl text-center lg:px-6">
            <Typography className="" level={"heading2"}>
              {CONTENT.toolkit.heading}
            </Typography>
            <MotionDiv
              className="mt-20 flex flex-wrap justify-center gap-4"
              variants={{
                visible: {
                  transition: {
                    delayChildren: 0,
                    staggerChildren: 0.2,
                  },
                },
              }}
              initial="hidden"
              animate="visible"
            >
              {CONTENT.toolkit.tools.map(({ name, icon: Icon, url }) => (
                <MotionCardLink
                  key={name}
                  href={url}
                  target="_blank"
                  variants={fadeAndSlideInFromLeft}
                >
                  <CardContent className="flex gap-4">
                    <Icon className="shrink-0" size={32} />
                    <Typography level={"heading3"}>{name}</Typography>
                  </CardContent>
                </MotionCardLink>
              ))}
            </MotionDiv>
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Page;
