import { type NextPage } from "next";
import Head from "next/head";

import { Avatar, AvatarContainer, AvatarGroup } from "@ui/Avatar";
import { Section } from "@ui/Section";
import { Container } from "@ui/Container";
import { Palette } from "@ui/Palette";
import { AppNavHeader } from "@/components/composite/AppNavHeader";
import { Button, ButtonGroup } from "@ui/Button";
import { Card, CardContent } from "@ui/Card";
import { Typography } from "@ui/Typography";
import { Alert } from "@ui/Alert";

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen overflow-hidden bg-base-100 pb-20 dark:bg-base-900">
        <AppNavHeader />
        <Section>
          <Container>
            <Palette />
          </Container>
        </Section>

        <Section palette="accent">
          <Container className="space-y-8">
            <AvatarGroup>
              <Avatar
                size="sm"
                src="https://placekitten.com/200/200"
              >{`CF`}</Avatar>
              <Avatar size="sm">{`CF`}</Avatar>
              <Avatar
                size="sm"
                src={"https://placekitten.com/240/240"}
              >{`CF`}</Avatar>
              <Avatar size="sm">{`+5`}</Avatar>
            </AvatarGroup>
            <AvatarGroup>
              <Avatar
                size="md"
                src="https://placekitten.com/200/200"
              >{`CF`}</Avatar>
              <Avatar size="md">{`CF`}</Avatar>
              <Avatar
                size="md"
                src={"https://placekitten.com/240/240"}
              >{`CF`}</Avatar>
              <Avatar size="md">{`+5`}</Avatar>
            </AvatarGroup>
            <AvatarGroup>
              <Avatar
                size="lg"
                src="https://placekitten.com/200/200"
              >{`CF`}</Avatar>
              <Avatar size="lg">{`CF`}</Avatar>
              <Avatar
                size="lg"
                src={"https://placekitten.com/240/240"}
              >{`CF`}</Avatar>
              <Avatar size="lg">{`+5`}</Avatar>
            </AvatarGroup>
          </Container>
        </Section>

        <Section>
          <Container>
            <ul className="space-y-4">
              <li>
                <Button intent="secondary">click</Button>
              </li>
              <li>
                <Button size="lg" intent="primary">
                  clock
                </Button>
              </li>
              <li>
                <Button intent="destructive">clack</Button>
              </li>
              <li>
                <Button disabled>clack</Button>
              </li>
              <li>
                <ButtonGroup>
                  <Button intent="secondary">click</Button>
                  <Button intent="secondary">clock</Button>
                  <Button intent="secondary">clack</Button>
                </ButtonGroup>
              </li>
            </ul>
          </Container>
        </Section>

        <Section>
          <Container>
            <Card palette="surface" elevation="high">
              <CardContent>
                <AvatarContainer>
                  <Avatar src="https://placekitten.com/220/220">{`CF`}</Avatar>
                  <div>
                    <Typography level="heading3">Cat Catterson</Typography>
                    <Typography level="body" color="weaker">
                      Head of CATering
                    </Typography>
                  </div>
                </AvatarContainer>
              </CardContent>
            </Card>
          </Container>
        </Section>

        <Section>
          <Container className="space-y-4">
            <Alert title="Success alert" status="success">
              Alert body. Some text or maybe some JSX goes here.
            </Alert>
            <Alert title="Info alert" status="info">
              Alert body. Some text or maybe some JSX goes here.
            </Alert>
            <Alert title="Warning alert" status="warning">
              Alert body. Some text or maybe some JSX goes here.
            </Alert>
            <Alert title="Danger alert" status="danger">
              Alert body. Some text or maybe some JSX goes here.
            </Alert>
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Page;
