import { type NextPage } from "next";
import Head from "next/head";

import { Avatar, AvatarContainer, AvatarGroup } from "@ui/Avatar";
import { Section } from "@ui/Section";
import { Container } from "@ui/Container";
import { Palette } from "@ui/Palette";
import { AppNavHeader } from "@/components/composite/AppNavHeader";
import { Button, ButtonGroup } from "@ui/Button";
import { Card, CardContent } from "@ui/Card";
import { Typography } from "@ui/Typography";
import { Alert } from "@ui/Alert";
import { FiArrowLeft, FiArrowRight, FiPlus } from "react-icons/fi";
import { Input, InputAdornment, InputGroup } from "@ui/Input";
import {
  SplitContent,
  SplitContentLeft,
  SplitContentRight,
} from "@ui/SplitContent";

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen overflow-hidden bg-base-100 pb-20 dark:bg-base-900">
        <AppNavHeader />
        <Section>
          <Container>
            <Palette />
          </Container>
        </Section>

        <Section>
          <Container>
            <Typography level="heading1" color="base">
              hello dude.
            </Typography>
            <Typography level="heading1" color="weak">
              hello dude.
            </Typography>
            <Typography level="heading1" color="weaker">
              hello dude.
            </Typography>
            <Typography level="heading1" color="primary">
              hello dude.
            </Typography>
          </Container>
        </Section>

        <Section palette="accent">
          <Container className="space-y-8">
            <AvatarGroup>
              <Avatar
                size="sm"
                src="https://placekitten.com/200/200"
              >{`CF`}</Avatar>
              <Avatar size="sm">{`CF`}</Avatar>
              <Avatar
                size="sm"
                src={"https://placekitten.com/240/240"}
              >{`CF`}</Avatar>
              <Avatar size="sm">{`+5`}</Avatar>
            </AvatarGroup>
            <AvatarGroup>
              <Avatar
                size="md"
                src="https://placekitten.com/200/200"
              >{`CF`}</Avatar>
              <Avatar size="md">{`CF`}</Avatar>
              <Avatar
                size="md"
                src={"https://placekitten.com/240/240"}
              >{`CF`}</Avatar>
              <Avatar size="md">{`+5`}</Avatar>
            </AvatarGroup>
            <AvatarGroup>
              <Avatar
                size="lg"
                src="https://placekitten.com/200/200"
              >{`CF`}</Avatar>
              <Avatar size="lg">{`CF`}</Avatar>
              <Avatar
                size="lg"
                src={"https://placekitten.com/240/240"}
              >{`CF`}</Avatar>
              <Avatar size="lg">{`+5`}</Avatar>
            </AvatarGroup>
          </Container>
        </Section>

        <Section>
          <Container>
            <ul className="space-y-4">
              <li>
                <Button intent="secondary">click</Button>
              </li>
              <li>
                <Button size="lg" intent="primary">
                  clock
                </Button>
              </li>
              <li>
                <Button intent="destructive">clack</Button>
              </li>
              <li>
                <Button disabled>clack</Button>
              </li>
              <li>
                <ButtonGroup>
                  <Button intent="secondary">
                    <FiArrowLeft size={24} />
                  </Button>
                  <Button intent="secondary">
                    <FiPlus size={24} />
                  </Button>
                  <Button intent="secondary">
                    <FiArrowRight size={24} />
                  </Button>
                </ButtonGroup>
              </li>
            </ul>
          </Container>
        </Section>

        <Section>
          <Container>
            <Card palette="base" elevation="low">
              <CardContent />
            </Card>
            <Card className="mt-6" palette="accent-raised" elevation="high">
              <CardContent>
                <AvatarContainer>
                  <Avatar src="https://placekitten.com/220/220">{`CF`}</Avatar>
                  <div>
                    <Typography level="heading3">Cat Catterson</Typography>
                    <Typography level="body" color="weaker">
                      Head of CATering
                    </Typography>
                  </div>
                </AvatarContainer>
              </CardContent>
            </Card>
          </Container>
        </Section>

        <Section>
          <Container className="space-y-4">
            <Alert title="Success alert" status="success">
              Alert body. Some text or maybe some JSX goes here.
            </Alert>
            <Alert title="Info alert" status="info">
              Alert body. Some text or maybe some JSX goes here.
            </Alert>
            <Alert title="Warning alert" status="warning">
              Alert body. Some text or maybe some JSX goes here.
            </Alert>
            <Alert title="Danger alert" status="danger">
              Alert body. Some text or maybe some JSX goes here.
            </Alert>
          </Container>
        </Section>

        <Section>
          <Container className="grid grid-cols-1 flex-col gap-4 sm:grid-cols-2">
            <Input placeholder="example@email.com" />
            <Input value="a" pattern="[0-9]*" />
            <Input disabled value="N/A" />
            <InputGroup>
              <InputAdornment>https://</InputAdornment>
              <Input placeholder="maxrandle.co.nz" />
            </InputGroup>
            <InputGroup className="sm:col-span-2">
              <Input />
              <InputAdornment>to</InputAdornment>
              <Input />
            </InputGroup>
            <InputGroup>
              <InputAdornment>$</InputAdornment>
              <Input />
            </InputGroup>
            <InputGroup>
              <Input />
              <InputAdornment>kg</InputAdornment>
            </InputGroup>
          </Container>
        </Section>

        <Section>
          <Container>
            <SplitContent>
              <SplitContentLeft>
                <Card>
                  <CardContent>
                    <Typography>First</Typography>
                  </CardContent>
                </Card>
              </SplitContentLeft>
              <SplitContentRight>
                <Card>
                  <CardContent>
                    <Typography>Second</Typography>
                  </CardContent>
                </Card>
              </SplitContentRight>
              <SplitContentRight>
                <Card>
                  <CardContent>
                    <Typography>Third</Typography>
                  </CardContent>
                </Card>
              </SplitContentRight>
              <SplitContentLeft>
                <Card>
                  <CardContent>
                    <Typography>Fourth</Typography>
                  </CardContent>
                </Card>
              </SplitContentLeft>
              <SplitContentLeft>
                <Card>
                  <CardContent>
                    <Typography>Fifth</Typography>
                  </CardContent>
                </Card>
              </SplitContentLeft>
            </SplitContent>
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Page;
