import { type NextPage } from "next";
import Head from "next/head";

import { Avatar, AvatarGroup } from "@/components/Avatar";
import { Section } from "@/components/Section";
import { Container } from "@/components/Container";
import { Palette } from "@/components/Palette";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen overflow-hidden bg-base-100 pb-20 dark:bg-base-900">
        <Section>
          <Container>
            <Palette />
          </Container>
        </Section>

        <Section palette="primary">
          <Container>
            <AvatarGroup>
              <Avatar src="https://placekitten.com/200/200">{`CF`}</Avatar>
              <Avatar>{`CF`}</Avatar>
              <Avatar src={"https://placekitten.com/240/240"}>{`CF`}</Avatar>
              <Avatar>{`+5`}</Avatar>
            </AvatarGroup>
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Home;
