import { type NextPage } from "next";
import Head from "next/head";

import { Avatar, AvatarGroup } from "@/components/ui/Avatar";
import { Section } from "@/components/ui/Section";
import { Container } from "@/components/ui/Container";
import { Palette } from "@/components/ui/Palette";
import {
  XLogoIcon,
  XLogoIconLower,
  XLogoIconUpper,
} from "@/components/Icons/XLogoIcon";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen overflow-hidden bg-base-100 pb-20 dark:bg-base-900">
        <Section>
          <Container>
            <Palette />
          </Container>
        </Section>

        <Section palette="primary">
          <Container>
            <AvatarGroup>
              <Avatar src="https://placekitten.com/200/200">{`CF`}</Avatar>
              <Avatar>{`CF`}</Avatar>
              <Avatar src={"https://placekitten.com/240/240"}>{`CF`}</Avatar>
              <Avatar>{`+5`}</Avatar>
            </AvatarGroup>
          </Container>
        </Section>

        <Section>
          <Container>
            <XLogoIcon size={96}>
              <XLogoIconUpper className="fill-primary-300 dark:fill-base-500" />
              <XLogoIconLower className="fill-primary-700 dark:fill-white" />
            </XLogoIcon>
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Home;
