import { type NextPage } from "next";
import Head from "next/head";

import { Section } from "@ui/Section";
import { Container } from "@ui/Container";
import { AnimatedBrandLogo } from "@/components/brand/AnimatedBrandLogo";
import { ButtonLink } from "@ui/Button";
import { motion } from "framer-motion";
import { ROUTES } from "@/config/routes";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen overflow-hidden bg-base-100 pb-20 dark:bg-base-900">
        <Section>
          <Container className="flex flex-col items-center">
            <AnimatedBrandLogo />
            <motion.div
              className="mt-20"
              variants={{
                hidden: {
                  opacity: 0,
                  y: 8,
                },
                visible: {
                  opacity: 1,
                  y: 0,
                },
              }}
              initial="hidden"
              animate="visible"
              transition={{
                delay: 3,
                duration: 1,
                ease: "easeOut",
              }}
            >
              <ButtonLink
                className="shadow-lg drop-shadow-glow-md"
                size="lg"
                intent="primary"
                href={ROUTES.about.root}
              >
                Enter
              </ButtonLink>
            </motion.div>
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Home;
